name: 2. Test

on:
  workflow_run:
    workflows: ["1. Lint"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install workspace dependencies
        run: |
          uv pip install --system -e .

      - name: Install backend dependencies
        run: |
          cd backend
          uv pip install --system -e .

      - name: Install frontend dependencies
        run: |
          cd frontend
          uv pip install --system -e .

      - name: Run backend tests
        run: |
          cd backend
          uv run pytest tests/ -v --cov=src/backend --cov-report=xml --cov-report=term

      - name: Run frontend tests
        run: |
          cd frontend
          uv run pytest tests/ -v --cov=src/frontend --cov-report=xml --cov-report=term

      - name: Upload backend coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

      - name: Upload frontend coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./frontend/coverage.xml
          flags: frontend
          name: frontend-coverage
